swagger: "2.0"
info:
  description: "This is my first REST API. It allows you to read and modify Users and their Movies."
  version: "1.0.0"
  title: "My first REST API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "user"
  description: "Everything about your Users"
- name: "movie"
  description: "Everything about your Movies"
schemes:
- "https"
- "http"
paths:
  /users:
    post:
      tags:
      - "user"
      summary: "Add a new user"
      description: ""
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that will be added"
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
            avatar:
              type: string
            age:
              type: number
      responses:
        200:
          description: "Success"
